"""add configurable equipment and training types

Revision ID: 2563dc9b268c
Revises: 376bcd73ec7e
Create Date: 2026-04-02 17:10:06.997744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2563dc9b268c'
down_revision = '376bcd73ec7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('has_details', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('has_expiration', sa.Boolean(), nullable=True),
    sa.Column('expiration_years', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_equipment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('equipment_type_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_types.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'equipment_type_id', name='uq_member_equipment')
    )
    op.drop_table('member_equipment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_equipment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('has_hf', sa.BOOLEAN(), nullable=True),
    sa.Column('has_dual_band', sa.BOOLEAN(), nullable=True),
    sa.Column('dual_band_watts', sa.TEXT(), nullable=True),
    sa.Column('has_digital_winlink', sa.BOOLEAN(), nullable=True),
    sa.Column('has_backup_power', sa.BOOLEAN(), nullable=True),
    sa.Column('backup_power_duration', sa.TEXT(), nullable=True),
    sa.Column('has_field_deployable', sa.BOOLEAN(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('member_equipment_items')
    op.drop_table('training_types')
    op.drop_table('equipment_types')
    # ### end Alembic commands ###
