"""add member profiles events training taskbooks commlogs

Revision ID: 376bcd73ec7e
Revises: e31996b0ab7e
Create Date: 2026-04-02 15:44:53.085286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376bcd73ec7e'
down_revision = 'e31996b0ab7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('callsign', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('street', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('zip_code', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.Text(), nullable=True),
    sa.Column('preferred_comm', sa.Text(), nullable=True),
    sa.Column('phone_privacy', sa.Boolean(), nullable=True),
    sa.Column('interest_skywarn', sa.Boolean(), nullable=True),
    sa.Column('interest_ares_auxcomm', sa.Boolean(), nullable=True),
    sa.Column('background_check', sa.Boolean(), nullable=True),
    sa.Column('mi_volunteer_registry', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('task_book_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('has_hf', sa.Boolean(), nullable=True),
    sa.Column('has_dual_band', sa.Boolean(), nullable=True),
    sa.Column('dual_band_watts', sa.Text(), nullable=True),
    sa.Column('has_digital_winlink', sa.Boolean(), nullable=True),
    sa.Column('has_backup_power', sa.Boolean(), nullable=True),
    sa.Column('backup_power_duration', sa.Text(), nullable=True),
    sa.Column('has_field_deployable', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('training_type', sa.Text(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('certificate_number', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_book_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['task_book_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('has_nts_liaison', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('siren_test_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['siren_test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_task_book_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('officer1_id', sa.Integer(), nullable=True),
    sa.Column('officer2_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['officer1_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['officer2_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task_book_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'task_id', name='uq_member_task')
    )
    op.create_table('comm_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_name', sa.Text(), nullable=False),
    sa.Column('activation_number', sa.Text(), nullable=True),
    sa.Column('op_period_start', sa.DateTime(), nullable=False),
    sa.Column('op_period_end', sa.DateTime(), nullable=False),
    sa.Column('net_name_or_position', sa.Text(), nullable=True),
    sa.Column('operator_name', sa.Text(), nullable=False),
    sa.Column('operator_callsign', sa.Text(), nullable=True),
    sa.Column('prepared_by', sa.Text(), nullable=True),
    sa.Column('prepared_date', sa.Date(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'member_id', name='uq_event_member')
    )
    op.create_table('comm_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comm_log_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('from_callsign', sa.Text(), nullable=True),
    sa.Column('from_msg_num', sa.Text(), nullable=True),
    sa.Column('to_callsign', sa.Text(), nullable=True),
    sa.Column('to_msg_num', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['comm_log_id'], ['comm_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_assignments_member_id', 'members', ['member_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assignments_member_id', type_='foreignkey')
        batch_op.drop_column('member_id')

    op.drop_table('comm_log_entries')
    op.drop_table('event_attendance')
    op.drop_table('comm_logs')
    op.drop_table('member_task_book_progress')
    op.drop_table('events')
    op.drop_table('task_book_tasks')
    op.drop_table('member_trainings')
    op.drop_table('member_equipment')
    op.drop_table('task_book_levels')
    op.drop_table('members')
    # ### end Alembic commands ###
