"""add performance indexes

Revision ID: 898fdbab6bea
Revises: 2563dc9b268c
Create Date: 2026-04-02 21:09:16.734519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898fdbab6bea'
down_revision = '2563dc9b268c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comm_log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comm_log_entries_comm_log_id'), ['comm_log_id'], unique=False)

    with op.batch_alter_table('event_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_attendance_member_id'), ['member_id'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_date'), ['date'], unique=False)

    with op.batch_alter_table('member_trainings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_trainings_member_id'), ['member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_trainings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_trainings_member_id'))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_date'))
        batch_op.drop_index(batch_op.f('ix_events_category'))

    with op.batch_alter_table('event_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_attendance_member_id'))

    with op.batch_alter_table('comm_log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comm_log_entries_comm_log_id'))

    # ### end Alembic commands ###
