"""rename test fields: activated->sound_ok, condition_ok->vegetation_damage_ok, remove passed column

Revision ID: bbde4c981608
Revises: de6cff780cca
Create Date: 2026-03-30 16:18:02.255908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbde4c981608'
down_revision = 'de6cff780cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sound_ok', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('vegetation_damage_ok', sa.Boolean(), nullable=False))
        batch_op.drop_column('condition_ok')
        batch_op.drop_column('activated')
        batch_op.drop_column('passed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passed', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('activated', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('condition_ok', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('vegetation_damage_ok')
        batch_op.drop_column('sound_ok')

    # ### end Alembic commands ###
